### ISSUE TITLE
Posibility to geolocate without street

### ISSUE THREAD

**Issue by josaur** [KeudellCoding/HumHub-Modules-UserMap#4]
In some contexts were using this tool not everybody has or wants to put in his street. So it would be great to make pull the geolocation based on the city also. Nice would be a checkbox in the adminpanel if to decide if the geocoding is using streets or not.

**Comment by KarlKeu00** [comment]
It is difficult to create an input mask for this application purpose. I will continue to work on this issue in the future.
However, since the latest version, you can customise the method that prepares the address for the API interface.

**Comment by josaur** [comment]
Hey thanks. Right now we changed the code as workaround. So we commented out those parts with the street. Right now my Webdev skills aren't good enough to add this button myself. Sorry for that

**Comment by josaur** [comment]
Hi i have en working Solution for this issue with the possibility to push it back. It deactivates the checks for the streets globaly and takes them out from the geocoding. They will not be shown anymore on the map.
![grafik](https://user-images.githubusercontent.com/61060743/183088993-212cb3bd-b0d4-4946-a22c-106cd711a919.png)

**Comment by josaur** [comment]
https://github.com/KeudellCoding/HumHub-Modules-UserMap/pull/12
