### ISSUE TITLE
Adding an random jitter to the geolocation

### ISSUE THREAD

**Issue by josaur** [KeudellCoding/HumHub-Modules-UserMap#5]
Normally using geolocation with people in the same city there is the problem, that all the markers are at the same place. In other context I used an random method to add an offset to each individual point. This would also cover the privacy of people if there is a geolocation based on streetnames.

**Comment by KarlKeu00** [comment]
Is this really necessary? Actually leaflet.markercluster groups the points and shows all points separately when clicked. I am currently working on the ability to edit the formatted address - then you can leave out the house number.

**Comment by KarlKeu00** [comment]
Since the last version it is now possible to override the methods that are responsible for finding the geolocations.

**Comment by josaur** [comment]
> Is this really necessary? Actually leaflet.markercluster groups the points and shows all points separately when clicked. I am currently working on the ability to edit the formatted address - then you can leave out the house number.

Not that much, the main point was for privacy things. The other thing was to have an better overview if there a many people at the same position.
