### ISSUE TITLE
The possibility of using OpenLayers (OSM), or other free alternatives.

### ISSUE THREAD

**Issue by perepou** [KeudellCoding/HumHub-Modules-UserMap#7]
The possibility of using OpenLayers (OSM), or other free alternatives. Thanks

First of all thank you for your development.
Would it be possible to use OpenLayers (or other free options) as alternatives to Google/Mapbox/Here?

I believe that in TikiWiki there are modules based on OpenLayers.

All the best.

**Comment by KarlKeu00** [comment]
Done in v1.2.3 :)
Unfortunately, I have not found a way to write a generic way to read API interfaces. As an alternative, you can now completely overwrite the method that is responsible for this.
